srtpProj/srtpApp/urls.py
from django.urls import path

from . import views

app_name = 'srtpApp'
urlpatterns = [
    path('', views.index, name='index'),                                            #首页
    path('newSecInfo/', views.newSecInfo, name = 'newSecInfo'),                     # 新建课堂
    path('checkSec/', views.checkSec, name='checkURL'),                             #查询
    path('checkSecInfo/<int:secID>/', views.checkSecInfo, name='checkInfoURL'),     #查询结果
]

srtpProj/srtpProj/urls.py
from argparse import Namespace
from tkinter.font import names
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView 
from srtpApp import views
urlpatterns = [
    path('', RedirectView.as_view(url='/app/')),        #访问http://127.0.0.1:8000/时自动重定向到 http://127.0.0.1:8000/app/
    path('app/', include('srtpApp.urls',namespace='srtpApp')),              #路由分配到 srtpApp的urlConf
    path('admin/', admin.site.urls),
]

srtpProj/srtpApp/models.py
from ast import Mod
from calendar import FRIDAY, THURSDAY, TUESDAY, WEDNESDAY
from pyexpat import model
from random import choices
from statistics import mode
from tabnanny import verbose
from xml.etree.ElementTree import tostring
from django.db import models

# Create your models here.

class ClassGrade(models.Model):
    class_name = models.CharField(max_length=256)
    def __str__(self):
        return self.class_name

class Student(models.Model):
    #主键
    stuID = models.CharField(max_length=16, verbose_name="Student ID",primary_key=True)
    stuname = models.CharField(max_length=32, verbose_name='student\'s name')
    class_name = models.ForeignKey(ClassGrade, on_delete=models.CASCADE)

    def __str__(self):
        return self.stuID

class Course(models.Model):
    course_name = models.CharField(max_length=64,verbose_name="Course Name")
    def __str__(self):
        return self.course_name

class Section(models.Model):
    course_name = models.ForeignKey(Course, on_delete=models.CASCADE)
    # 如需要设置integerField的最大最小值需要使用   验证器: https://docs.djangoproject.com/zh-hans/4.0/ref/validators/#django.core.validators.MinValueValidator
    #1-18为有效值
    week_num = models.IntegerField(verbose_name='Which week')
    # 枚举类
    class Weekday(models.IntegerChoices):
        Monday = 1, '周一'
        TUESDAY = 2, '周二'
        WEDNESDAY = 3, '周三'
        THURSDAY = 4, '周四'
        FRIDAY = 5, '周五'
    weekday_num = models.IntegerField(choices = Weekday.choices, verbose_name='Which day in a week')
    section_num = models.IntegerField(verbose_name='Which section')
    capture_num = models.IntegerField("All capture times",default=0)
    class Meta:
        unique_together = (('course_name','week_num','weekday_num','section_num'),)
    def __str__(self) -> str:
        return "课堂ID:"+str(self.id)
    

class Status(models.Model):
    #主键ID自动生成
    stuID = models.ForeignKey(Student, on_delete=models.CASCADE)
    sectionID = models.ForeignKey(Section, on_delete=models.CASCADE)
    focus_num = models.IntegerField(verbose_name="Focus Times")
    unfocus_num = models.IntegerField('unFocus Times', default=0)
    signin_bool = models.BooleanField('Sign in?')
    late_bool = models.BooleanField('late?',default=False)
    leaveEarly_bool = models.BooleanField('leave early?',default=False)
    signin_time = models.DateTimeField('Time of sign in',null=True, blank=True)
    signout_time = models.DateTimeField('Time of sign out',null=True, blank=True)
    def __str__(self) -> str:
        return str(self.stuID) + '-' + str(self.signin_bool)

srtpProj/srtpApp/forms.py
from secrets import choice
from turtle import textinput

from .public import *

from django import forms
from .models import Course

class newSecInfoForm(forms.Form):
    course_name = forms.ChoiceField(choices=(),widget=forms.Select(attrs={'style':'margin-left:30px;width:150px'}))
    week_num = forms.ChoiceField(choices=TupleClass.weekTuple(),widget=forms.Select(attrs={'style':'margin-left:58px;width:150px'}))
    weekday_num = forms.ChoiceField(choices=TupleClass.weekdayTuple,widget=forms.Select(attrs={'style':'margin-left:58px;width:150px'}))
    section_num = forms.ChoiceField(choices=TupleClass.secTuple(),widget=forms.Select(attrs={'style':'margin-left:58px;width:150px'}))
    ip_addr = forms.CharField(widget=forms.TextInput(attrs={'style':'width:150px;margin-left:4px'}))
    def __init__(self, *args, **kwargs):
        super(newSecInfoForm, self).__init__(*args, **kwargs)
        self.fields['course_name'].choices = Course.objects.all().values_list('id','course_name') 

class checkSecForm(forms.Form):
    course_name = forms.ChoiceField(choices=(),widget=forms.Select(attrs={'class':'form-control','style':'width:400px;'}))
    week_num = forms.ChoiceField(choices=TupleClass.weekTuple(),widget=forms.Select(attrs={'class':'form-control','style':'width:400px;'}))
    weekday_num = forms.ChoiceField(choices=TupleClass.weekdayTuple,widget=forms.Select(attrs={'class':'form-control','style':'width:400px;'}))
    section_num = forms.ChoiceField(choices=TupleClass.secTuple(),widget=forms.Select(attrs={'class':'form-control','style':'width:400px;'}))

    def __init__(self, *args, **kwargs):
        super(checkSecForm, self).__init__(*args, **kwargs)
        self.fields['course_name'].choices = Course.objects.all().values_list('id','course_name')

srtpProj/srtpApp/views.py
import re
from django import http
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, request
from .forms import *
from .models import *
import json
from .ThreadCamera import *
from datetime import datetime,timedelta
import random
from django.views.decorators.csrf import csrf_exempt

import requests
import time
import cv2
# Create your views here.
weekdayDic = {1:'周一',2:'周二',3:'周三',4:'周四',5:'周五'}
v = None
section = None

def detectVideo():
    global v
    global section
    if section is not None:
        section = None
    if v is not None:
        if v.is_record:
            v.stop_record()

def index(request):
    detectVideo()
    return render(request, 'srtpApp/index.html')

def newSecInfo(request):
    global v
    global section
    error_info = ''
    form = newSecInfoForm()
    if request.method == 'POST':
        if 'submit' in request.POST:
            form = newSecInfoForm(request.POST)
            if form.is_valid():
                courseID = form.cleaned_data['course_name']
                courseObj = Course.objects.get(id = courseID)
                weekNum = form.cleaned_data['week_num']
                weekdayNum = form.cleaned_data['weekday_num']
                sectionNum = form.cleaned_data['section_num']
                ipStr = "http://"+ form.cleaned_data['ip_addr'] +":8080/?action=stream"
                try:
                    sec = Section.objects.get(course_name=courseObj, week_num=weekNum, weekday_num=weekdayNum,
                                              section_num=sectionNum)
                except:
                    if v is None or section is not None:
                        detectVideo()
                        v = VideoCamera()
                    v.start_record()

                    section = Section(course_name = courseObj, week_num = weekNum, weekday_num = weekdayNum, section_num = sectionNum)
                    return render(request, 'srtpAPP/newSecInfo.html', {"form": form, 'showFlag': "True", 'ipStr':ipStr})
                else:
                    error_info = '已经创建了该课堂'

        elif 'delete' in request.POST:
            Section.objects.all().delete()
            return render(request, 'srtpAPP/newSecInfo.html', {"form":form,'message':"删除成功"})
        elif 'end' in request.POST:
        # 控制 识别程序停止 读取json格式数据
            v.stop_record()
            with open(os.getcwd()+r"\srtpApp\jsonData\data.json","r",encoding='utf8') as f:
                jsonData = json.load(f)
        #存储section数据到 Section表中
            if section is not None:
                section.capture_num = jsonData["countCapture"]
                section.save()
            elif section is None:
                return HttpResponseRedirect(reverse('srtpApp:newSecInfo'))
        # 解析json数据存入 Status数据表中
            stuObjs = Student.objects.all()
            for stuObj in stuObjs:
            #获取当前stuObj的学号stuID
                stuID = stuObj.stuID

                # 获取json数据
                focusTime = jsonData[stuID]["detect_success"]
                count = jsonData[stuID]["count"]
                start = datetime.strptime(jsonData["startTime"], '%Y-%m-%d %H:%M:%S')
                end = datetime.strptime(jsonData["endTime"], '%Y-%m-%d %H:%M:%S')
            #将数据存入status数据表
                status = Status()
                status.stuID = stuObj
                status.sectionID = section
                status.focus_num = focusTime
                status.unfocus_num = count - focusTime
                if count != 0:
                    stuStart = datetime.strptime(jsonData[stuID]["start"], '%Y-%m-%d %H:%M:%S')
                    stuEnd = datetime.strptime(jsonData[stuID]["end"], '%Y-%m-%d %H:%M:%S')
                    status.signin_bool = True
                    if (stuStart - start) > timedelta(seconds=101):
                        status.late_bool = True
                    if (end - stuEnd) > timedelta(seconds=10):
                        status.leaveEarly_bool = True
                elif count == 0:
                    status.signin_bool = False
                    status.late_bool = False
                    status.leaveEarly_bool = False

                status.save()

            return HttpResponseRedirect(reverse("srtpApp:index"))

    return render(request, 'srtpApp/newSecInfo.html', {"form":form, 'error_info':error_info, 'showFlag': ""})

def checkSec(request):
    detectVideo()
    form = checkSecForm()
    if request.method == 'POST':
        form = checkSecForm(request.POST)
        if form.is_valid():
            courseID = form.cleaned_data['course_name']
            courseObj = Course.objects.get(id = courseID)
            weekNum = form.cleaned_data['week_num']
            weekdayNum = form.cleaned_data['weekday_num']
            sectionNum = form.cleaned_data['section_num']
            try:
                sec = Section.objects.get(course_name = courseObj, week_num = weekNum, weekday_num = weekdayNum, section_num = sectionNum)
            except:
                return render(request, 'srtpApp/checkSec.html', {"form":form, "error_info":"未查询到该节课"})
            else:
                seq=(
                    'course='+str(courseObj.course_name), 
                    'weeks='+ str(weekNum), 
                    'weekday='+weekdayDic[int(weekdayNum)],
                    'sec='+str(sectionNum),
                    )
                getStr = '?' + '&'.join(seq)
                return HttpResponseRedirect(reverse('srtpApp:checkInfoURL', args=[sec.id])+getStr)
    return render(request, 'srtpApp/checkSec.html', {"form":form})

def checkSecInfo(request,secID):
    detectVideo()
    sec = Section.objects.get(id = secID)
    captureNum = sec.capture_num
    name=[]
    unfocus = []
    focus=[]
    unsign = ""
    late = ""
    early = ""
    statusObjs = Status.objects.filter(sectionID=sec)
    for statusObj in statusObjs:
        sName = str(statusObj.stuID.stuname)
        sfocus = statusObj.focus_num
        sunfocus = statusObj.unfocus_num
        name.append(sName)
        focus.append(sfocus)
        unfocus.append(sunfocus)
        if not statusObj.signin_bool:
            unsign += (" "+sName)
        if statusObj.late_bool:
            late += (" "+sName)
        if statusObj.leaveEarly_bool:
            early += (" "+sName)
    if not unsign: unsign="无"
    if not late: late="无"
    if not early: early="无"

    dic = {
        'name': json.dumps(name),
        'focus': json.dumps(focus),
        'unfocus': json.dumps(unfocus),
        'unsign': unsign,
        'late': late,
        'early': early,
        'captureNum': captureNum,
    }
    return render(request, 'srtpApp/checkSecInfo.html', dic)

srtpProj/srtpApp/templates/srtpApp/checkSec.html
{% extends 'srtpApp/index.html' %}
{% load static %}

{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href= {% static "css/public3.css" %}>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <title>查询</title>
{% endblock %}

{% block content %}
    <!-- 主体部分 -->
    <div id="body" style="position:relative;left:300px;top:50px;">
        <!-- 
        <p id="info1" style="width:400px;height:15px;text-align:center;color:red;font-size: 14px;position: relative;left:200px"></p>
        <p id="info2" style="width:400px;height:15px;text-align:center;color:red;font-size: 14px;position: relative;left:200px"></p>
        <p id="info3" style="width:400px;height:15px;text-align:center;color:red;font-size: 14px;position: relative;left:200px"></p>
        -->
        <form action = {% url 'srtpApp:checkURL' %} method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group" style="width:500px;position: relative;left:200px">
                {{ form.course_name.errors }}
                <label for="{{ form.course_name.id_for_label }}">课程名称:</label>
                {{ form.course_name }}
            </div>

            <div class="form-group " style="width:400px;position: relative;left:200px">
                {{ form.week_num.errors }}
                <label for="{{ form.week_num.id_for_label }}">周数:</label>
                {{ form.week_num }}
            </div>

            <div class="form-group" style="width:500px;position: relative;left:200px">
                {{ form.weekday_num.errors }}
                <label for="{{ form.weekday_num.id_for_label }}">周几:</label>
                {{ form.weekday_num }}
            </div>

            <div class="form-group" id="upload" style="margin-top:5px;width:400px;position: relative;left:200px">
                {{ form.section_num.errors }}
                <label for="{{ form.section_num.id_for_label }}">节数:</label>
                {{ form.section_num }}
            </div>
            <div>
                <button name="submit" id="button" class="btn btn-primary" style="margin-top:5px;width:400px;position:relative;left:200px">确定</button>
                <p style="width:400px;height:15px;text-align:right;color:red;font-size: 14px;position:relative;left:200px">{{ error_info }}</p>
            </div>
        </form>
    </div>

{% endblock %}

{% block jsScript %}
<!--<script src= {% static "js/newSecInfo.js" %}></script>-->
{% endblock %}

srtpProj/srtpApp/templates/srtpApp/checkSecInfo.html
{% extends 'srtpApp/index.html' %}
{% load static %}

{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href={% static 'css/public2.css' %}>
    <script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <style>
        p{
            margin-bottom: 30px;
            padding-left:50px;
            font-size: 15px;
            color: red;
            text-align: left;
        }
        #labelInfo{
            font-weight:bold;
            margin-left:30px;
        }
        #Info label{
            margin-top: 10px;
        }
        #Info{
            width: 90%;
            height:auto;
            margin-top:30px;
            margin-left:5%;
            margin-right:5%;
            border: 2px dashed;
            border-color: #3E3E7D;
            padding: 30px;
        }
    </style>
    <title>学生课堂表现</title>
{% endblock %}

{% block content %}
    <!-- 主体部分 -->
    <div id="body">
        <div id="picture" style="min-width:700px;height:1000px;margin-top:20px"></div>
        <div id="tips">tips</div>
        <span id="point">此图表用来展示学生上课各状态次数统计</span>
    </div>
    <label for="Info" id="labelInfo">上课情况总结:</label>
    <div id="Info">
        <label for="nosignin">未签到:</label>
        <p id="nosignin">{{ unsign }}</p>
        <label for="late">迟到:</label>
        <p id="late">{{ late }}</p>
        <label for="early">早退:</label>
        <p id="early">{{ early }}</p>
    </div>
{% endblock %}

{% block jsScript %}
    <script>
        var stuName = {{ name|safe }};
        var focusTime = {{ focus|safe }};
        var unfocusTime = {{ unfocus|safe }};
        var AllNum = {{ captureNum }};

        $(document).ready(function() {
        let obj = new Object();
        obj = GetRequest();
        let { course, weeks, weekday, sec } = obj;

        function GetRequest() {
            var url = location.search; //获取url中"?"符后的字串
            var theRequest = new Object();
            if (url.indexOf("?") != -1) {
                var str = url.substr(1);
                strs = str.split("&");
                for (var i = 0; i < strs.length; i++) {
                    theRequest[strs[i].split("=")[0]] = decodeURI(strs[i].split("=")[1]);
                }
            }
            return theRequest;
        }

        var chart = {
            type: 'bar'
        };
        var title = {
            text: `${course} `
        };
        var subtitle = {
            text: `   第${weeks}周  ${weekday}  第${sec}节`
        };
        var xAxis = {
            categories: stuName,
            title: {
                text: "学生姓名",
                align: 'high'
            }
        };
        var yAxis = {
            min: 0,
            max: AllNum,
            title: {
                text: '课堂状态次数分布',
                align: 'high'
            },
            labels: {
                overflow: 'justify'
            }
        };
        var tooltip = {
            valueSuffix: '次'
        };
        var plotOptions = {
            bar: {
                dataLabels: {
                    enabled: true
                }
            },
            series: {
                stacking: 'normal'
            }
        };
        var legend = {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'top',
            x: -40,
            y: 100,
            floating: true,
            borderWidth: 1,
            backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
            shadow: true
        };
        var credits = {
            enabled: false
        };

        var series = [
            {
                name: '不专注',
                data: unfocusTime,
                color: '#B73838',
            },
            {
                name: '专注',
                data: focusTime,
                color: '#6BA4FA',
            },
        ];

        var json = {};
        json.chart = chart;
        json.title = title;
        json.subtitle = subtitle;
        json.tooltip = tooltip;
        json.xAxis = xAxis;
        json.yAxis = yAxis;
        json.series = series;
        json.plotOptions = plotOptions;
        json.legend = legend;
        json.credits = credits;
        $('#picture').highcharts(json);

    });
    </script>
{% endblock %}

srtpProj/srtpApp/templates/srtpApp/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href={% static 'css/public.css' %}>
    <title>学生听课状态检测系统</title>
    {% endblock %}
</head>

<body>
    <!-- 整体页面 -->
    <div id="container">
        <!-- header部分 -->
        <div id="header">
            <!-- 头部图片 -->
            <img src={% static 'img/title1.jpg' %} alt="..">
        </div>

        <!-- 导航部分 -->
        <div id="banner">
            <!-- 一级菜单 -->
            <ul class="banner">
                <li class="nav_item i1">
                    <a href={% url 'srtpApp:index' %} class="firsta"><span>首页</span></a>
                </li>
                <li class="nav_item i2">
                    <a href={% url 'srtpApp:newSecInfo' %}><span class="li_name">新增课堂</span></a>
                </li>
                <li class="nav_item i4">
                    <a href={% url 'srtpApp:checkURL' %}><span class="li_name">学生课堂表现</span></a>
                </li>
                <li class="nav_item i5">
                    <a href="https://www.swjtu.edu.cn/"><span class="li_name">学校官网</span></a>
                </li>
            </ul>
        </div>                 

        {% block content %}
        <!-- 主体部分 -->
        <div id="body">         
            <!-- 图文新闻部分 -->
            <div class="middle">
                <!-- 图文消息 -->
                <div class="news">
                    <!-- 上部 -->
                    <div class="newstop">
                        <div class="news_left">新闻动态</div>
                        <div class="news_right"><a href="https://www.baidu.com/" target="_blank">更多</a></div>
                    </div>
                    <div id="hr"></div>

                    <div class="mid_all">
                        <!-- 中间轮播图加文字新闻 -->
                        <div class="mid">
                            <!-- 轮播图 -->
                            <div id="contain">
                                <div class="box">
                                    <div class="img">
                                        <ul>
                                            <li class="on"><img src={% static 'img/4.jpg' %} alt=".."></li>
                                            <li><img src={% static 'img/3.jpg' %} alt=".."></li>
                                            <li><img src={% static 'img/5.jpg' %} alt=".."></li>
                                            <li><img src={% static 'img/1.jpg' %} alt=".."></li>
                                            <li><img src={% static 'img/2.jpg' %} alt=".."></li>
                                        </ul>
                                    </div>

                                    <div class="checkout">
                                        <ul>
                                            <li class="this">1</li>
                                            <li>2</li>
                                            <li>3</li>
                                            <li>4</li>
                                            <li>5</li>
                                        </ul>
                                    </div>

                                    <div class="btn">
                                        <div class="left_btn">&lt</div>
                                        <div class="right_btn">&gt</div>
                                    </div>
                                </div>
                            </div>

                            <!-- 下部图文新闻链接 -->
                            <div class="newsbottom">
                                <h2>NEWS</h2>
                                <a target="_blank" href="https://www.qianzhan.com/analyst/detail/220/180727-626786c1.html" title="2018年智慧教室发展现状与趋势分析 将呈现多样化路径教学等方向">2018年智慧教室发展现状与趋势分析</a>
                                <a target="_blank" href="http://lemd.cuc.edu.cn/2018/1027/c604a16146/page.htm" title="让智慧发生 智慧教室未来前景看好">让智慧发生 智慧教室未来前景看好</a>
                                <a target="_blank" href="http://mini.eastday.com/bdmip/181028231525795.html" title="一篇文章看懂高校未来智慧教室建设趋势">一篇文章看懂高校未来智慧教室建设趋势</a>
                                <a target="_blank" href="http://www.qianjia.com/html/2018-10/30_309717.html" title="我国智慧教室行业发展现状及趋势分析">我国智慧教室行业发展现状及趋势分析</a>
                                <a target="_blank" href="http://www.sohu.com/a/233375232_177272" title="路在何方？智慧教室面临的问题与未来">路在何方？智慧教室面临的问题与未来</a>
                                <a target="_blank" href="http://www.sohu.com/a/232697017_426518" title="智慧教室面临的“智慧”问题怎么破？">智慧教室面临的“智慧”问题怎么破？</a>
                                <a target="_blank" href="http://blog.sina.com.cn/s/blog_1523cfcf90102xrm9.html" title="智慧教室在教学中的应用">智慧教室在教学中的应用</a>
                            </div>
                        </div>


                    </div>

                </div>

            </div>
        </div>
        {% endblock %}
    </div>

    {% block jsScript %}
    <script src={% static 'js/jquery-3.3.1.min.js' %}></script>
    <script src={% static 'js/index.js' %}></script>
    {% endblock %}

</body>

</html>

srtpProj/srtpApp/templates/srtpApp/newSecInfo.html
{% extends 'srtpApp/index.html' %}
{% load static %}

{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href= {% static "css/public3.css" %}>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet" media="screen"> 
    <script src={% static "js/jquery-3.6.0.min.js" %}></script>
    <script type="text/javascript">
        var showFlag = '{{ showFlag }}'
        $(document).ready(function(){
            if(showFlag == "True"){
                $(":button#button1").attr('disabled',true);
            }
        });
    </script>
    <style>
        .wrap {
            width: auto;
            margin-left=10px;
            margin-right=10px;
            height:800px;
        }
        #left{
            margin-top:-10px;
            box-sizing: border-box;
            width: 40%;
            height: 100%;
            background: #d4d6e5 ;
            float:left;
            padding-top:150px;
            }
        #right{
            margin-top:-10px;
            background-color: white;
            float: left;
            box-sizing: border-box;
            padding-left: 50px;
            width: 60%;
            height:100%
        }
    </style>

    <title>新增课堂</title>

{% endblock %}

{% block content %}
    <!-- 主体部分 -->
    <div class="wrap">
        <!-- 左边内容 -->
        <div id="left" class="left">
                <!--
                <p id="info1" style="width:400px;height:15px;text-align:center;color:red;font-size: 14px;position: relative;left:200px"></p>
                <p id="info2" style="width:400px;height:15px;text-align:center;color:red;font-size: 14px;position: relative;left:200px"></p>
                <p id="info3" style="width:400px;height:15px;text-align:center;color:red;font-size: 14px;position: relative;left:200px"></p>
                -->
                <form action = {% url 'srtpApp:newSecInfo' %} method="POST">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    <h3 style="width:500px;position: relative;left:180px;margin-bottom: 30px;">新增课堂信息：</h3>
                    <div class="form-group" style="width:500px;position: relative;left:200px">
                        {{ form.course_name.errors }}
                        <label for="{{ form.course_name.id_for_label }}">课程名称:</label>
                        {{ form.course_name }}
                    </div>
        
                    <div class="form-group " style="width:400px;position: relative;left:200px">
                        {{ form.week_num.errors }}
                        <label for="{{ form.week_num.id_for_label }}">周数:</label>
                        {{ form.week_num }}
                    </div>
        
                    <div class="form-group" style="width:500px;position: relative;left:200px">
                        {{ form.weekday_num.errors }}
                        <label for="{{ form.weekday_num.id_for_label }}">周几:</label>
                        {{ form.weekday_num }}
                    </div>
        
                    <div class="form-group" id="upload" style="margin-top:5px;width:400px;position: relative;left:200px">
                        {{ form.section_num.errors }}
                        <label for="{{ form.section_num.id_for_label }}">节数:</label>
                        {{ form.section_num }}
                    </div>
                    <div class="form-group" style="width:500px;position: relative;left:200px">
                        {{ form.ip_addr.errors }}
                        <label for="{{ form.ip_addr.id_for_label }}">摄像头ip地址:</label>
                        {{ form.ip_addr }}
                    </div>
                    <p style="width:400px;height:15px;text-align:center;color:red;font-size: 14px;position: relative;left:230px">{{ error_info }}</p>
                    <button name="submit" id="button1" class="btn btn-primary" style="margin-top:5px;width:300px;position: relative;left:200px">确定并开始上课</button>
                    <br>
                    <button name="delete" id="button2" class="btn btn-primary" style="margin-top:20px;width:300px;position: relative;left:200px">删除所有课堂</button>
                    {% if message %}
                        <script>
                            alert('{{ message }}');
                        </script>
                    {% endif %}
                </form>
        </div>
        <!-- 右边内容 -->
        <div id="right" class="right">  
            {% if showFlag %}
                <p style="color:red;font-weight:bold;">请勿跳转其他页面！！！如果点击下课按钮未跳转到主页则该节课没有记录</p>
                <p style="">正在上课中。。。</p>
<!--     "http://192.168.36.100:8080/?action=stream"           <video id="video" style="margin-top:50px;width:700px;"></video>-->
                <img src={{ ipStr }}/>

                <form action = {% url 'srtpApp:newSecInfo' %} method="POST">
                    {% csrf_token %}
                    <button name="end" id="button3" class="btn btn-primary" style="width:200px;margin-top:5px;">下课</button>
                </form>
            {% endif %}
        </div>
    </div>


{% endblock %}

{% block jsScript %}
<!--<script src= {% static "js/newSecInfo.js" %}></script>-->
<!--<script src = {% static "js/camera.js" %}></script>-->
{% endblock %}